name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Publish .NET Discord Bot (Self-Contained)
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true -o ./publish

    - name: Deploy to Remote Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "./publish/*, ./Dockerfile"
        target: "/home/${{ secrets.SERVER_USER }}/discord-bot"

    - name: Run Bot on Remote Server with Docker
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/discord-bot/publish
          docker stop discord-bot-container || true
          docker rm discord-bot-container || true
          docker build -t discord-bot .
          docker run -d --name discord-bot-container discord-bot
